### ISSUE TITLE
Any ETA on opensourcing Calligraphus?

### ISSUE THREAD

**Issue by stantonk** [facebook/jcommon#31]
This would be great since scribe is EOL'd :) :)

**Comment by electrum** [comment]
Take a look at Fluentd: http://www.fluentd.org/

**Comment by srash** [comment]
also kafka:
http://kafka.apache.org/

**Comment by facebook-github-bot-3** [comment]
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.

**Comment by srash** [comment]
There is presently no ETA to open source calligraphus.
