### ISSUE TITLE
ConcurrentLinkedHashMap --> Caffeine when Java-8 based 

### ISSUE THREAD

**Issue by ben-manes** [facebook/jcommon#33]
There is an unused dependency on an older version of [ConcurrentLinkedHashMap](https://code.google.com/p/concurrentlinkedhashmap/). If it is used internally, please consider upgrading to [Caffeine](https://github.com/ben-manes/caffeine) when Java 8 based. CLHM is now end-of-life and maintained only for Java 6 users. Guava's cache is in a similar state as there is no one left familiar with the implementation and Guava must remain Android compatible (~JDK6). Since I am no longer involved with Guava I can't speak to that cache's future, other than say there is no current owner.

Caffeine is a Java 8 rewrite of Guava's cache with additional features and [higher performance](https://github.com/ben-manes/caffeine/wiki/Benchmarks).

**Comment by srash** [comment]
thanks for the info—a java 8 upgrade is in the pipeline.  I’ll switch to caffeine at that time.

can you point me to where the dependency is now?   if it’s truly unused (and I can’t find any uses either), I might as well axe it for now and pull caffeine in if/when we need it

**Comment by ben-manes** [comment]
https://github.com/facebook/jcommon/blob/master/pom.xml#L296

**Comment by srash** [comment]
ah, no code references?  (hence ‘unused’)

**Comment by ben-manes** [comment]
Unused, declared from maven terminology. It may be transients referred to which is okay as poms are versioned too.

**Comment by srash** [comment]
got it—i was able to a clean test w/o it listed, so likely it’s just stale..

thanks

**Comment by facebook-github-bot-3** [comment]
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.

**Comment by srash** [comment]
we've upgraded to java 8; but i'm going to just remove as its unused

**Comment by ben-manes** [comment]
Sounds good. If you're using Guava's cache you might want to switch. Last time I talked to the Guava team they planned on switching internally once Google is Java 8 based.

**Comment by srash** [comment]
just reading your doc:  how did you find using soft/weak references plays with GC?
a few years ago (java 6), I saw this not work out so good with caching.  does java 8 CMS or G1 work better?

**Comment by ben-manes** [comment]
I'm not a fan of soft references. I do consider weak references useful, but only in certain situations where there is a clear design trade-off. I think libraries should be opinionated but not restrictive, so I do favor adequately warning users while giving them the features they consider necessary. There is also a need to retain backwards compatibility with Guava. In general I prefer, and have focused on, size-based caching.

Currently size based caching linearly scales at 33% of CHM and in v2 I'm hoping to boost that to 90% using eviction policy tricks. That's still exploratory, though.

__Long story__
Since the beginning of Guava (Google Collections) the team was enamored by weak/soft/phantom references. There was a lot of hostility expressed towards those that disagreed and ignoring of production workloads in favor of microbenchmarks that never GC'd. `MapMaker` was written as a fork of CHM to optimize the memory use of soft references compared to the `ReferenceMap` decorator, primarily in response to a thread on jsr166 where JBoss wanted to contribute a similar class. There were repeated claims that reference caching was the only way forward in Java 5+ because a size based cache couldn't be concurrent and that the GC should be responsible for all memory management.

CLHM was the first concurrent Java cache that didn't use background threads or have an O(n) eviction penalty (e.g. Clock policies). When I joined Google a lot of big teams wouldn't switch to MapMaker and the main evangelist had left. So my proposal provided an O(1) size, O(1) eviction (MapMaker's was O(lg n)), and removed the background reference collecting thread (was causing a lot of issues). MapMaker was overhauled, became CacheBuilder, and legacy internal caching libraries were removed. I was a 20%er who bootstrapped, code reviewed, and advised the Guava team member (Charles).

Caffeine is a rewrite based on what I originally wanted Guava to look like (no reason to fork the hash table), performance fixes that I could never get in, and various other improvements. Java 8 just seemed like a good excuse for putting in all the work and enough time had passed that it wouldn't be (politically) offensive.

So I'm not an advocate of soft references and did a lot to kill them off at Google. But once you support weak references for valid usages, soft are trivial to add and despite warnings someone may have a good reason for using them.

**Comment by ben-manes** [comment]
Sorry, I ranted and never answered your question.

A weak reference should be collectable in a minor GC. A soft-reference usually requires 2 major GC's, if I recall correctly. G1 changes often enough that its hard to say how it currently handles it, but by breaking the heap into small pools there is potential for more prompt collection. JEP-132 (More Prompt Finalization) might improve that.

I don't think the advise has changed much and they should be used very judiciously. For good performance one should minimize the work of the GC, whereas reference collection increases it.

**Comment by srash** [comment]
it was years ago, but yea, soft was the one that i recall caused gc pressure

thanks!

**Comment by ben-manes** [comment]
Thanks for adding a Caffeine impl. =)
