### ISSUE TITLE
A Bug in HyperLogLog implemetation

### ISSUE THREAD

**Issue by zhou-jered** [facebook/jcommon#40]
Hey, Guys
I find a serialization bug in HyperLogLog, I can not deserialize correctly from the byte array that I had serialized in before, after I checkout the HyperLogLog code, I find you forgot to calculate the nonZeroBucket. The code below is the test code. I am trying fix this bug, if you think I am right, please merge my PR, Thanks
`package me.line.hiro.filterAndAggregator;

import me.line.hiro.common.algorithm.HyperLogLog;

import org.junit.Test;

public class HyperLogLogTest {

	@Test
	public void testSeriaizer() {
		HyperLogLog hll = new HyperLogLog(16);
		for (int i = 0; i < 10000; i++) {
			hll.add(i);
		}
		System.out.println("original eatiminate: " + hll.estimate());
		System.out.println("original data:");
		opBucket(hll);
		System.out.println("currentSum: " + hll.getCurrentSum() + " nonZeroBcuket: " + hll.getNonZeroBuckets());

		System.out.println();
		HyperLogLog anothHll = new HyperLogLog(hll.buckets());
		System.out.println("deSerializer estiminate: " + anothHll.estimate());
		System.out.println("DeSerializer data : ");
		opBucket(anothHll);
		System.out.println("currentSum: " + anothHll.getCurrentSum() + " nonZeroBcuket: "
				+ anothHll.getNonZeroBuckets());
	}

	private void opBucket(HyperLogLog hll) {
		int[] bucket = hll.buckets();
		int len = Math.min(20, bucket.length);
		for (int i = 0; i < len; i++) {
			System.out.print(bucket[i] + " ");
		}
		System.out.println();
	}
}
`

`original eatiminate: 8975
original data:
9 10 9 13 9 12 10 9 10 9 9 12 15 10 9 10 
currentSum: 0.019195556640625 nonZeroBcuket: 16

deSerializer estiminate: 8975
DeSerializer data : 
9 10 9 13 9 12 10 9 10 9 9 12 15 10 9 10 
currentSum: 0.019195556640625 nonZeroBcuket: 0`

**Comment by srash** [comment]
@martint can you verify this? I'll merge after you check
